services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: nabr-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nabr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-nabr_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-nabr}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server (All-in-One with SQLite, Web UI, and CLI)
  temporal:
    image: temporalio/temporal:1.4.1
    container_name: nabr-temporal
    command:
      - server
      - start-dev
      - --ip
      - "0.0.0.0"
      - --db-filename
      - "/data/temporal.db"
    ports:
      - "7233:7233"  # gRPC endpoint
      - "8233:8233"  # Web UI
    volumes:
      - ./data/temporal:/data
    healthcheck:
      test: ["CMD", "temporal", "operator", "cluster", "health", "--address", "localhost:7233"]
      interval: 10s
      timeout: 5s
      retries: 30

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: nabr-backend
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_healthy
    environment:
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=${POSTGRES_USER:-nabr}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-nabr_db}
      - POSTGRES_PORT=5432
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE:-default}
      - TEMPORAL_TASK_QUEUE=${TEMPORAL_TASK_QUEUE:-nabr-task-queue}
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
    command: uvicorn nabr.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # Temporal Worker
  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: nabr-worker
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_healthy
    environment:
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=${POSTGRES_USER:-nabr}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-nabr_db}
      - POSTGRES_PORT=5432
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE:-default}
      - TEMPORAL_TASK_QUEUE=${TEMPORAL_TASK_QUEUE:-nabr-task-queue}
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
    command: python -m nabr.temporal.worker
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  temporal_data:
    driver: local
